services:
  mongodb:
    image: mongo:8.0
    restart: always
    ports:
      - "27017:27017"
    command: ["mongod","--auth","--bind_ip_all"]
    env_file:
      - .env.mongo
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init:/docker-entrypoint-initdb.d:ro
    networks: [portfolio_network]

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks: [portfolio_network]
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5
    logging:
      driver: "json-file"
      options: { max-size: "10m", max-file: "3" }
    command: redis-server --save 60 1 --loglevel verbose

  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SKIP_DB_DURING_BUILD: "true"        # build-time only
        SKIP_REDIS_DURING_BUILD: "true"     # build-time only
    restart: always
    ports:
      - "3003:3000"
    volumes:
      - ./public/images:/app/public/images:rw
    depends_on:
      redis:
        condition: service_healthy
    networks: [portfolio_network]
    env_file:
      - .env.production
    environment:                         # runtime overrides
      SKIP_DB_DURING_BUILD: "false"
      SKIP_REDIS_DURING_BUILD: "false"
    logging:
      driver: "json-file"
      options: { max-size: "10m", max-file: "3" }

networks:
  portfolio_network:
    driver: bridge

volumes:
  mongodb_data:
  redis_data:
